"""empty message

Revision ID: 733dfb6008d9
Revises: 
Create Date: 2018-11-24 18:04:03.508701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733dfb6008d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('supplier', sa.String(length=50), nullable=True),
    sa.Column('preparation', sa.String(length=1500), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('ingredients', sa.String(length=500), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.Column('hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Relations',
    sa.Column('id_relacao', sa.Integer(), nullable=False),
    sa.Column('id_recipe', sa.Integer(), nullable=False),
    sa.Column('id_ingredient', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ingredient'], ['Ingredients.id'], ),
    sa.ForeignKeyConstraint(['id_recipe'], ['Recipes.id'], ),
    sa.PrimaryKeyConstraint('id_relacao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Relations')
    op.drop_table('Version')
    op.drop_table('Recipes')
    op.drop_table('Ingredients')
    # ### end Alembic commands ###
